version: '3.8'

services:
  api:
    build:
      context: ./sdv-api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./sdv-api:/app
    command: ["cargo", "run", "--release"]

  frontend:
    build:
      context: ./sdv-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./sdv-web:/app
    environment:
      - API_URL=http://api
